# Generated by Django 5.1.3 on 2024-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('poem', 'Стихотворение'), ('song', 'Песня'), ('story', 'Рассказ')], default='poem', max_length=10)),
                ('lyrics', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
